services:
  product-service:
    build:
      context: .
    container_name: spring-product-service
    ports:
      - "9500:9500"
    networks:
      - store_front_network
      - product-service
    depends_on:
      - product-db
    environment:
      DB_URL: jdbc:postgresql://product-db:5432/product_ms
      DB_USERNAME: proxi
      DB_PASSWORD: 123
      REGISTRY_SERVICE: http://registry-service:8761/eureka/


  product-db:
    image: postgres
    environment:
      POSTGRES_DB: product_ms
      POSTGRES_USER: proxi
      POSTGRES_PASSWORD: 123
    ports:
      - "5435:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - product-service


networks:
  product-service:
    driver: bridge
  store_front_network:
    external: true

volumes:
  postgres_data: {}